name: CI-CD

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: 20.x
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Deploy (fake)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}"

      - name: Gerar flag
        id: flag
        run: |
          echo "YSBhdWxh" > flag.txt

      - name: Expor resultado
        run: cat flag.txt